angular.module('justVoteApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/create.html',
    "<div class=\"container\"> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-7 col-lg-7\"> <h2>Initiate a Vote</h2> <h4>Just be curious how others think</h4> <div class=\"vote-img\"> <img src=\"images/flat-icon/pencil-retina.svg\"> </div> </div> <div class=\"visible-sm-12 hidden-md hidden-lg welcome-title\"> <h2>Initiate a Vote</h2> <h4>Just be curious how others think</h4> </div> <div class=\"col-xs-12 col-sm-12 col-md-5 col-lg-5\"> <div class=\"panel panel-default panel-item panel-login\"> <h5 class=\"login-title\">Create <span class=\"pull-right\"><span class=\"fui-plus\"></span></span></h5> <div class=\"alert-login\" ng-bind=\"error\"></div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-new\"></span></span> <input type=\"text\" class=\"form-control\" placeholder=\"Title for your vote\" ng-model=\"title\"> </div> </div> <div class=\"form-group\" id=\"marker\" align=\"center\" ng-repeat=\"item in list\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-radio-checked\"></span></span> <input type=\"text\" class=\"form-control\" placeholder=\"Type an option\" ng-model=\"item.value\"> </div> </div> <div class=\"form-group\" align=\"center\"> <button type=\"button\" class=\"btn btn-primary btn-lg btn-block btn-login\" ng-click=\"addOption()\">Add Option</button> </div> <div class=\"form-group\" align=\"center\"> <button type=\"button\" class=\"btn btn-primary btn-lg btn-block btn-login\" ng-click=\"clear()\">Clear</button> </div> <div class=\"form-group\" align=\"center\"> <button type=\"button\" class=\"btn btn-primary btn-lg btn-block btn-login\" ng-click=\"submit()\" ng-disabled=\"disabledSubmit\" ng-bind=\"submitBtnText\"></button> </div> </div> </div> </div> </div>"
  );


  $templateCache.put('views/item.html',
    "<div class=\"container\"> <div class=\"row row-title\"> <div class=\"col-md-12 col-lg-12\"> <h2>Vote It</h2> <h4>Choose and show your opinion</h4> </div> </div> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-4 col-lg-3\"> <div class=\"todo\"> <div class=\"todo-search\"> <strong>Navigator</strong> <span class=\"pull-right\"><span class=\"fui-list-large-thumbnails\"></span></span> </div> <ul> <li class=\"todo-done\"> <div class=\"todo-content item-navigator\"> <span class=\"fui-checkbox-checked\"></span> <span> {{vote | total}} Attenders</span> </div> </li> <li class=\"todo-done item-navigator\"> <div class=\"todo-content\"> <span class=\"fui-time\"></span> <span> {{vote.date | timeConvert}}</span> </div> </li> <li class=\"todo-done item-navigator\"> <div class=\"todo-content\"> <a type=\"button\" ng-href=\"#/list\" class=\"btn btn-primary\"><span class=\"fui-arrow-left\"></span>Back to list</a> </div> </li> </ul> </div> </div><!-- sidebar --> <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-9 item-content\" ng-hide=\"showResult\"> <h4 class=\"vote-item-title\">{{vote.title}}</h4> <div class=\"panel-item panel-item-voted\">Choose one of the following options.</div> <div ng-repeat=\"(key, value) in vote.options\"> <input type=\"radio\" value=\"{{key}}\" name=\"item\" ng-click=\"select(key)\"><label class=\"option-label\"> &nbsp;{{value.content}}</label> </div> <br> <button class=\"btn btn-primary btn-vote\" ng-click=\"submit()\" ng-disabled=\"disableSubmit\"><span class=\"fui-check\"></span>&nbsp;&nbsp;Vote</button> <hr> </div><!-- choose view --> <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-9 item-content\" ng-show=\"showResult\"> <h4 class=\"vote-item-title\">{{vote.title}}</h4> <div class=\"panel-item panel-item-voted\">You have voted. Thank you! Here is the review.</div> <div ng-repeat=\"(key, value) in vote.options\"> <strong>{{value.content}}</strong> - {{value.rate}} out of {{totalRate}} <div class=\"progress\"> <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"{{value.rate/totalRate*100}}\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: {{value.rate/totalRate*100}}%\">{{value.rate/totalRate*100 | number:1}}%</div> </div> </div> </div><!-- result view --> </div><!-- row --> </div><!-- container -->"
  );


  $templateCache.put('views/list.html',
    "<div class=\"container\"> <div class=\"row row-title\"> <div class=\"col-md-12 col-lg-12\"> <h2>Vote List</h2> <h4>Pick an item you interested</h4> </div> </div> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-4 col-lg-3\"> <div class=\"todo\"> <div class=\"todo-search\"> <strong>Filter</strong> <span class=\"pull-right\"><span class=\"fui-gear\"></span></span> </div> <ul> <li class=\"todo-done\"> <div class=\"todo-content\"> <span class=\"item-num-control\">Total items: {{votes.length}}</span> </div> </li> <li class=\"todo-done\"> <div class=\"todo-content\"> <span class=\"item-num-control\">Items per Page: {{itemPerPage}}</span> </div> </li> <li class=\"todo-done\"> <div class=\"todo-content\"> <span class=\"item-num-control\">Current Page: {{selectPage}}</span> </div> </li> <li> <div class=\"todo-content\"> <label class=\"checkbox\" for=\"hideVoted\"> <input type=\"checkbox\" ng-model=\"showLatest\" name=\"showLatest\" ng-change=\"filterLatest(5)\"> <strong>Show latest polls</strong> </label> </div> </li> </ul> </div> </div><!-- sidebar --> <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-9\"> <div class=\"panel panel-default panel-item\" ng-repeat=\"(key, value) in votes | range:selectPage:itemPerPage\"> <div class=\"panel-body\"> <h5 class=\"vote-title\"><a ng-href=\"#/item/{{value.$id}}\">{{value.title}}</a></h5> <p><small> <span class=\"fui-checkbox-checked\"></span> <span>{{value | total}} Attended | </span> <span class=\"fui-time\"></span> <span>{{value.date | timeConvert}}</span> <span class=\"fui-star-2 pull-right\"></span> </small></p> </div> </div> <div class=\"btn-group\"> <button ng-repeat=\"vote in votes | pageCount:itemPerPage\" ng-click=\"selected($index + 1)\" class=\"btn btn-primary\">{{$index + 1}}</button> </div> </div><!-- main content --> </div><!-- row --> </div><!-- container -->"
  );


  $templateCache.put('views/loading-spanner.html',
    "<div class=\"sk-circle\" ng-if=\"isRouteLoading\"> <div class=\"sk-circle1 sk-child\"></div> <div class=\"sk-circle2 sk-child\"></div> <div class=\"sk-circle3 sk-child\"></div> <div class=\"sk-circle4 sk-child\"></div> <div class=\"sk-circle5 sk-child\"></div> <div class=\"sk-circle6 sk-child\"></div> <div class=\"sk-circle7 sk-child\"></div> <div class=\"sk-circle8 sk-child\"></div> <div class=\"sk-circle9 sk-child\"></div> <div class=\"sk-circle10 sk-child\"></div> <div class=\"sk-circle11 sk-child\"></div> <div class=\"sk-circle12 sk-child\"></div> </div>"
  );


  $templateCache.put('views/login.html',
    "<div class=\"container\"> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-7 col-lg-7\"> <h2>Welcome, voter !</h2> <h4>Sign in and stand by what you like</h4> <div class=\"vote-img\"> <img src=\"images/flat-icon/vote-retina.svg\"> </div> </div> <div class=\"visible-sm-12 hidden-md hidden-lg welcome-title\"> <h2>Welcome, voter !</h2> <h4>Sign in and stand by what you like</h4> </div> <div class=\"col-xs-12 col-sm-12 col-md-5 col-lg-5\"> <div class=\"panel panel-default panel-item panel-login\"> <h5 class=\"login-title\">Login <span class=\"pull-right\"><span class=\"fui-user\"></span></span></h5> <div class=\"alert-login\" ng-bind=\"error\" ng-show=\"error\"></div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-mail\"></span></span> <input type=\"email\" class=\"form-control\" placeholder=\"E-Mail\" ng-model=\"email\"> </div> </div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-lock\"></span></span> <input type=\"password\" class=\"form-control\" placeholder=\"Password\" ng-model=\"passwd\"> </div> </div> <div class=\"form-group\" align=\"center\"> <button type=\"button\" class=\"btn btn-primary btn-lg btn-block btn-login\" ng-click=\"login()\" ng-disabled=\"!(email&&passwd) || loginDisabled\" ng-bind=\"loginBtnText\"></button> </div> <p class=\"register-link\" style=\"text-align: center\">Not a voter?&nbsp;<a ng-href=\"#/register\">Register</a></p> </div> </div> </div> </div>"
  );


  $templateCache.put('views/register.html',
    "<div class=\"container\"> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-7 col-lg-7\"> <h2>Become a voter</h2> <h4>Toward the world of polls and votes</h4> <div class=\"vote-img\"> <img src=\"images/flat-icon/loop-retina.svg\"> </div> </div> <div class=\"visible-sm-12 hidden-md hidden-lg welcome-title\"> <h2>Become a voter</h2> <h4>Towards the world of polls and votes</h4> </div> <div class=\"col-xs-12 col-sm-12 col-md-5 col-lg-5\"> <div class=\"panel panel-default panel-item panel-login\"> <h5 class=\"login-title\">Register <span class=\"pull-right\"><span class=\"fui-plus-circle\"></span></span></h5> <div class=\"alert-login\" ng-bind=\"error\" ng-show=\"error\"></div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-mail\"></span></span> <input type=\"email\" class=\"form-control\" placeholder=\"Your E-Mail\" ng-model=\"email\"> </div> </div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-lock\"></span></span> <input type=\"password\" class=\"form-control\" placeholder=\"Choose a Password\" ng-model=\"passwd1\"> </div> </div> <div class=\"form-group\" align=\"center\"> <div class=\"input-group\"> <span class=\"input-group-addon\"><span class=\"fui-lock\"></span></span> <input type=\"password\" class=\"form-control\" placeholder=\"Repeat your Password\" ng-model=\"passwd2\"> </div> </div> <div class=\"form-group\" align=\"center\"> <button type=\"button\" class=\"btn btn-primary btn-lg btn-block btn-login\" ng-click=\"create()\" ng-disabled=\"!(email && passwd1 && passwd2)\" ng-bind=\"createBtnText\"></button> </div> <p class=\"register-link\" style=\"text-align: center\">Already a voter?&nbsp;<a ng-href=\"#/login\">Login</a></p> </div> </div> </div> </div>"
  );


  $templateCache.put('views/user.html',
    "<div class=\"container\"> <div class=\"row row-title\"> <div class=\"col-md-12 col-lg-12\"> <h2>Vote History</h2> <h4>Review what you voted for</h4> </div> </div> <div class=\"row\"> <div class=\"hidden-xs hidden-sm col-md-4 col-lg-3\"> <div class=\"todo\"> <div class=\"todo-search\"> <strong>Filter</strong> <span class=\"pull-right\"><span class=\"fui-gear\"></span></span> </div> <ul> <li class=\"todo-done\"> <div class=\"todo-content\"> <label class=\"checkbox\" for=\"showNew\"> <input type=\"checkbox\" ng-model=\"showLatest\" name=\"showLatest\" ng-change=\"filterLatest(5)\"> <strong>Only show latest records</strong> </label> </div> </li> <li class=\"todo-done item-navigator\"> <div class=\"todo-content\"> <a type=\"button\" ng-href=\"#/list\" class=\"btn btn-primary\"><span class=\"fui-arrow-left\"></span>Back to list</a> </div> </li> </ul> </div> </div><!-- sidebar --> <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-9 history-wrapper\"> <div class=\"well well-info\"> <span class=\"fui-list-bulleted\" style=\"color: #1ABC9C\"></span> <span class=\"item-num-control\">Total items: {{records.length}} </span> </div><!-- list info --> <div class=\"col-sm-12 col-md-6 col-lg-4 history-item\" ng-repeat=\"record in records\"> <div class=\"history-item-content\"> <p><a ng-href=\"#/item/{{record.id}}\" title=\"{{record.title}}\">{{record.title}}</a></p> <span class=\"fui-checkbox-checked\"></span><span> Your choice: {{record.option}}</span><br> <span class=\"fui-time\"></span><span> {{record.date | timeConvert}}</span> </div> </div> <div class=\"col-sm-12 col-md-6 col-lg-4 history-item\"> <div class=\"history-item-content history-add-item\"> <p><a href=\"#/create\" title=\"Initial a new vote\">Initial a new vote</a></p> <span>&nbsp;</span><br> <span>&nbsp;</span> </div> </div> </div><!-- main content --> </div><!-- row --> </div><!-- container -->"
  );

}]);
